// ─────────────────────────────────────────────────────────────
//  AUTO-GENERATED PORTFOLIO PHOTO GROUPS (DO NOT EDIT DIRECTLY)
//  Generated by convert_assets.py
// ─────────────────────────────────────────────────────────────

export interface PhotoGroup {
  id: string;
  title: string;
  type: 'folder' | 'pdf' | 'general';
  images: string[];
}

export const convertedPhotoGroups: PhotoGroup[] = [
  {
    id: 'gift-city',
    title: 'Gift City',
    type: 'folder',
    images: [
      '/converted-photos/gift-city/1.webp',
      '/converted-photos/gift-city/2.webp',
      '/converted-photos/gift-city/3.webp',
      '/converted-photos/gift-city/4.webp',
      '/converted-photos/gift-city/5.webp',
      '/converted-photos/gift-city/6.webp',
      '/converted-photos/gift-city/7.webp',
    ],
  },
  {
    id: 'tandoor-story',
    title: 'Tandoor Story',
    type: 'folder',
    images: [
      '/converted-photos/tandoor-story/1.webp',
      '/converted-photos/tandoor-story/2.webp',
      '/converted-photos/tandoor-story/3.webp',
      '/converted-photos/tandoor-story/4.webp',
      '/converted-photos/tandoor-story/5.webp',
      '/converted-photos/tandoor-story/6.webp',
      '/converted-photos/tandoor-story/7.webp',
    ],
  },
  {
    id: 'general-showcase',
    title: 'General Design Showcase',
    type: 'general',
    images: [
      '/converted-photos/general-showcase/1.webp',
      '/converted-photos/general-showcase/2.webp',
      '/converted-photos/general-showcase/3.webp',
      '/converted-photos/general-showcase/4.webp',
      '/converted-photos/general-showcase/5.webp',
      '/converted-photos/general-showcase/6.webp',
    ],
  },
  {
    id: '3d-view-parents-room',
    title: 'View Parents Room (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/3d-view-parents-room/page-1.webp',
      '/converted-photos/3d-view-parents-room/page-2.webp',
      '/converted-photos/3d-view-parents-room/page-3.webp',
    ],
  },
  {
    id: 'kid-s-bedroom-washroom-3d',
    title: "Kid's Bedroom Washroom (3D Concept)",
    type: 'pdf',
    images: [
      '/converted-photos/kid-s-bedroom-washroom-3d/page-1.webp',
      '/converted-photos/kid-s-bedroom-washroom-3d/page-2.webp',
      '/converted-photos/kid-s-bedroom-washroom-3d/page-3.webp',
      '/converted-photos/kid-s-bedroom-washroom-3d/page-4.webp',
    ],
  },
  {
    id: 'master-bedroom-washroom-and-wardrobe-3d',
    title: 'Master Bedroom Washroom And Wardrobe (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/master-bedroom-washroom-and-wardrobe-3d/page-1.webp',
      '/converted-photos/master-bedroom-washroom-and-wardrobe-3d/page-2.webp',
      '/converted-photos/master-bedroom-washroom-and-wardrobe-3d/page-3.webp',
      '/converted-photos/master-bedroom-washroom-and-wardrobe-3d/page-4.webp',
      '/converted-photos/master-bedroom-washroom-and-wardrobe-3d/page-5.webp',
    ],
  },
  {
    id: 'f-floor-seating-area',
    title: 'F. Floor Seating Area (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/f-floor-seating-area/page-1.webp',
      '/converted-photos/f-floor-seating-area/page-2.webp',
      '/converted-photos/f-floor-seating-area/page-3.webp',
    ],
  },
  {
    id: 'guest-bedroom-revised-2-1',
    title: 'Guest Bedroom 2 (1) (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/guest-bedroom-revised-2-1/page-1.webp',
      '/converted-photos/guest-bedroom-revised-2-1/page-2.webp',
      '/converted-photos/guest-bedroom-revised-2-1/page-3.webp',
      '/converted-photos/guest-bedroom-revised-2-1/page-4.webp',
    ],
  },
  {
    id: 'guest-bedroom-revised-2',
    title: 'Guest Bedroom 2 (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/guest-bedroom-revised-2/page-1.webp',
      '/converted-photos/guest-bedroom-revised-2/page-2.webp',
      '/converted-photos/guest-bedroom-revised-2/page-3.webp',
      '/converted-photos/guest-bedroom-revised-2/page-4.webp',
    ],
  },
  {
    id: 'kitchen-3d-view',
    title: 'Kitchen View (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/kitchen-3d-view/page-1.webp',
      '/converted-photos/kitchen-3d-view/page-2.webp',
      '/converted-photos/kitchen-3d-view/page-3.webp',
      '/converted-photos/kitchen-3d-view/page-4.webp',
      '/converted-photos/kitchen-3d-view/page-5.webp',
      '/converted-photos/kitchen-3d-view/page-6.webp',
      '/converted-photos/kitchen-3d-view/page-7.webp',
    ],
  },
  {
    id: 'master-bedroom-3d-3',
    title: 'Master Bedroom 3 (3D Concept)',
    type: 'pdf',
    images: [
      '/converted-photos/master-bedroom-3d-3/page-1.webp',
      '/converted-photos/master-bedroom-3d-3/page-2.webp',
      '/converted-photos/master-bedroom-3d-3/page-3.webp',
    ],
  },
];
